### ISSUE TITLE
There is no sound

### ISSUE THREAD

**Issue by floydback** [ZVK/stretcher#1]
There is no any sound, why?

**Comment by ZVK** [comment]
This project is still under development, but I updated this repository with new commits this week. There is also a live demo you can test out using Chrome [here](http://soundbomb.media/stretcher/).

**Comment by floydback** [comment]
I have explore you code and find out two sad things:
1. [soundtouch](https://github.com/ZVK/soundtouch-js) working not like web audio api node element.
2. Soundtouch algorithm requires 100% buffered audio file before you can play and change pitch of it. So it impossible to use soundtouch without preloading.

am I right?

**Comment by ZVK** [comment]
Yes, you are correct.
